let productData = [
    {
        id: "k1",
        name: "Caramel Frapuccino",
        price: 50000,
        type: "tart",
        img: "assets/image/produk/kopi/k-1.jpg",
    },
    {
        id: "k2",
        name: "Cheese Cake",
        price: 300000,
        type: "tart",
        img: "assets/image/produk/kue/k-2.png",
    },
    {
        id: "k3",
        name: "Black Forest",
        price: 300000,
        type: "tart",
        img: "assets/image/produk/kue/k-3.png",
    },
    {
        id: "k4",
        name: "Birthday Cake",
        price: 400000,
        type: "tart",
        img: "assets/image/produk/kue/k-4.png",
    },
    {
        id: "k5",
        name: "Cookies and Cream",
        price: 300000,
        type: "tart",
        img: "assets/image/produk/kue/k-5.png",
    },
    {
        id: "k6",
        name: "Tiramissu",
        price: 300000,
        type: "tart",
        img: "assets/image/produk/kue/k-6.png",
    },
    {
        id: "k7",
        name: "Red Velvet",
        price: 300000,
        type: "tart",
        img: "assets/image/produk/kue/k-7.png",
    },
    {
        id: "k8",
        name: "Rainbow Cake",
        price: 300000,
        type: "tart",
        img: "assets/image/produk/kue/k-8.png",
    },

    // roti
    {
        id: "r1",
        name: "Roti Tawar",
        price: 25000,
        type: "roti",
        img: "assets/image/produk/roti/r-1.png",
    },
    {
        id: "r2",
        name: "Croissant",
        price: 25000,
        type: "roti",
        img: "assets/image/produk/roti/r-2.png",
    },
    {
        id: "r3",
        name: "Roti Unyil",
        price: 50000,
        type: "roti",
        img: "assets/image/produk/roti/r-3.png",
    },
    {
        id: "r4",
        name: "Roti Gandum",
        price: 30000,
        type: "roti",
        img: "assets/image/produk/roti/r-4.png",
    },
    {
        id: "r5",
        name: "Roti Baguette",
        price: 50000,
        type: "roti",
        img: "assets/image/produk/roti/r-5.png",
    },
    {
        id: "r6",
        name: "Donat",
        price: 7000,
        type: "roti",
        img: "assets/image/produk/roti/r-6.png",
    },
    {
        id: "r7",
        name: "Pizza",
        price: 25000,
        type: "roti",
        img: "assets/image/produk/roti/r-7.png",
    },
    {
        id: "r8",
        name: "Roti Cokelat",
        price: 15000,
        type: "roti",
        img: "assets/image/produk/roti/r-8.png",
    },

    // bolu
    {
        id: "b1",
        name: "Bolu Mentega",
        price: 65000,
        type: "bolu",
        img: "assets/image/produk/bolu/b-1.png",
    },
    {
        id: "b2",
        name: "Bolu Pandan",
        price: 65000,
        type: "bolu",
        img: "assets/image/produk/bolu/b-2.png",
    },
    {
        id: "b3",
        name: "Bolu Meranti",
        price: 100000,
        type: "bolu",
        img: "assets/image/produk/bolu/b-3.png",
    },
    {
        id: "b4",
        name: "Lapis Legit",
        price: 50000,
        type: "bolu",
        img: "assets/image/produk/bolu/b-4.png",
    },
    {
        id: "b5",
        name: "Bolu Lapis",
        price: 40000,
        type: "bolu",
        img: "assets/image/produk/bolu/b-5.png",
    },
    {
        id: "b6",
        name: "Bolu Macan",
        price: 40000,
        type: "bolu",
        img: "assets/image/produk/bolu/b-6.png",
    },
    {
        id: "b7",
        name: "Bolu Talas",
        price: 60000,
        type: "bolu",
        img: "assets/image/produk/bolu/b-7.png",
    },
    {
        id: "b8",
        name: "Bolu Kukus",
        price: 10000,
        type: "bolu",
        img: "assets/image/produk/bolu/b-8.png",
    },

    // kue kering
    {
        id: "kk1",
        name: "Cookies",
        price: 20000,
        type: "kue kering",
        img: "assets/image/produk/kue-kering/kk-1.png",
    },
    {
        id: "kk2",
        name: "Macaroon",
        price: 25000,
        type: "kue kering",
        img: "assets/image/produk/kue-kering/kk-2.png",
    },
    {
        id: "kk3",
        name: "Nastar",
        price: 75000,
        type: "kue kering",
        img: "assets/image/produk/kue-kering/kk-3.png",
    },
    {
        id: "kk4",
        name: "Kastengel",
        price: 75000,
        type: "kue kering",
        img: "assets/image/produk/kue-kering/kk-4.png",
    },
    {
        id: "kk5",
        name: "Putri Salju",
        price: 65000,
        type: "kue kering",
        img: "assets/image/produk/kue-kering/kk-5.png",
    },
    {
        id: "kk6",
        name: "Sagu Keju",
        price: 65000,
        type: "kue kering",
        img: "assets/image/produk/kue-kering/kk-6.png",
    },
    {
        id: "kk7",
        name: "Kue Kacang",
        price: 50000,
        type: "kue kering",
        img: "assets/image/produk/kue-kering/kk-7.png",
    },
    {
        id: "kk8",
        name: "Kue Semprit",
        price: 50000,
        type: "kue kering",
        img: "assets/image/produk/kue-kering/kk-8.png",
    },
];
